version: '2'

services:
  local-diffusers:
    build:
      context: .
    volumes:
#    - ./whls:/home/huggingface/output
    - ./EveryDream2trainer:/workspace/EveryDream2trainer
    - ./images:/workspace/images
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
